export const array = [
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
]



export const newArray = [
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
]



export const othArray = [
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
	{
		flag: false,
		btnText : '确定',
		trueShow : [false, false, false, false],
		falseShow : [false, false, false, false],
		isShow : false,
		height : '1308rpx', 
		paddingBottom : '40rpx',
		opacity: 0.3,
		bgc: ['', '', '', ''],
	},
]